openapi: 3.0.1
info:
    title: 'fake api'
    version: 1.0.0
    contact:
        email: metaapi@metaapi.com
        name: 'metaAPI Team'
    license:
        name: 'Apache 2.0'
        url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
servers:
    -
        url: 'http://localhost:8000/meta-api/services/fake/api'
        variables: {  }
        description: 'Main server'
paths:
    /getUser:
        parameters:
            -
                in: query
                name: id
                description: 'user id'
                schema:
                    type: integer
                required: true
        get:
            summary: 'get list of users'
            description: ''
            operationId: getUser
            responses:
                200:
                    description: OK
                    content:
                        application/json:
                            schema:
                                type: object
    /getPost:
        parameters:
            -
                in: query
                name: id
                description: 'post id'
                schema:
                    type: integer
                required: true
        get:
            summary: 'get lists of posts'
            description: ''
            operationId: getPost
            responses:
                200:
                    description: OK
                    content:
                        application/json:
                            schema:
                                type: object
security:
    -
        bearerAuth:
            - ''
components:
    securitySchemes:
        bearerAuth:
            type: http
            scheme: bearer
